{% set name = "stginga" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4fbd9b5e504c682638760c581c59a17109b31e08167b9a6bd19c87a01d05a28

build:
  noarch: python
  number: 0
  entry_points:
    - stginga = stginga.gingawrapper:_main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - python >=3.7
    - numpy
    - scipy >=0.18
    - astropy >=3
    - ginga >=2.7

test:
  requires:
    - pytest
  imports:
    - stginga
  commands:
    - stginga --help

about:
  home: https://www.github.com/spacetelescope/stginga
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Ginga products specific to STScI data analysis
  description: Ginga products specific to STScI data analysis
  doc_url: https://stginga.readthedocs.io
  dev_url: https://www.github.com/spacetelescope/stginga

extra:
  recipe-maintainers:
    - pllim
